
spring:
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      use-sql-comments: true
  datasource:
    url: jdbc:postgresql://localhost:5432/bccdb
    username: bccdb_user
    password: petkovapass